# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocoin',
            name='cap',
        ),
        migrations.RemoveField(
            model_name='cryptocoin',
            name='changeday',
        ),
        migrations.RemoveField(
            model_name='cryptocoin',
            name='changehour',
        ),
        migrations.RemoveField(
            model_name='cryptocoin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cryptocoin',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cryptocoin',
            name='url',
        ),
    ]
