# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180824_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoin',
            name='cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptocoin',
            name='changeday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptocoin',
            name='changehour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptocoin',
            name='changeweek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptocoin',
            name='image',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='cryptocoin',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptocoin',
            name='url',
            field=models.URLField(default=b''),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
    ]
